apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  restartPolicy: Always
  containers:
  - name: flask
    image: jinny1/gfgwebimage
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3