apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"